import * as advancedReports from "./advancedReports";

interface ReportData {
  title: string;
  description: string;
  data: any[];
  chartType: "bar" | "line" | "pie" | "area" | "table";
  generatedAt: string;
}

/**
 * Generate a simple HTML representation of a report
 * This can be converted to PDF using a service like Puppeteer or html2pdf
 */
export async function generateReportHTML(
  organizationId: number,
  reportId: string,
  organizationName: string = "CRM Professional"
): Promise<string> {
  try {
    const report = await advancedReports.generateReport(organizationId, reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    const generatedDate = new Date(report.generatedAt).toLocaleString();
    const tableHTML = generateTableHTML(report.data);

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${report.title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      color: #333;
      line-height: 1.6;
      background: #f5f5f5;
    }
    
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      padding: 40px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .header {
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .logo {
      font-size: 24px;
      font-weight: bold;
      color: #3b82f6;
      margin-bottom: 10px;
    }
    
    .organization {
      font-size: 14px;
      color: #666;
      margin-bottom: 20px;
    }
    
    .title {
      font-size: 28px;
      font-weight: bold;
      color: #1f2937;
      margin-bottom: 10px;
    }
    
    .description {
      font-size: 14px;
      color: #666;
      margin-bottom: 10px;
    }
    
    .meta {
      font-size: 12px;
      color: #999;
      margin-top: 10px;
    }
    
    .content {
      margin-top: 30px;
    }
    
    .chart-type {
      display: inline-block;
      background: #e0e7ff;
      color: #3b82f6;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
      margin-bottom: 20px;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    
    thead {
      background: #f3f4f6;
      border-bottom: 2px solid #e5e7eb;
    }
    
    th {
      padding: 12px;
      text-align: left;
      font-weight: 600;
      color: #1f2937;
      font-size: 13px;
    }
    
    td {
      padding: 12px;
      border-bottom: 1px solid #e5e7eb;
      font-size: 13px;
    }
    
    tbody tr:hover {
      background: #f9fafb;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
    
    .page-break {
      page-break-after: always;
    }
    
    @media print {
      body {
        background: white;
      }
      .container {
        box-shadow: none;
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">📊 ${organizationName}</div>
      <div class="organization">Report Generated: ${generatedDate}</div>
    </div>
    
    <div class="title">${report.title}</div>
    <div class="description">${report.description}</div>
    <div class="meta">Chart Type: <span class="chart-type">${report.chartType}</span></div>
    
    <div class="content">
      ${tableHTML}
    </div>
    
    <div class="footer">
      <p>This report was automatically generated by CRM Professional</p>
      <p>© ${new Date().getFullYear()} CRM Professional. All rights reserved.</p>
    </div>
  </div>
</body>
</html>
    `;

    return html;
  } catch (error) {
    console.error("Error generating report HTML:", error);
    throw error;
  }
}

/**
 * Generate HTML table from report data
 */
function generateTableHTML(data: any[]): string {
  if (!Array.isArray(data) || data.length === 0) {
    return "<p>No data available</p>";
  }

  const headers = Object.keys(data[0]);
  const headerRow = headers.map((h) => `<th>${escapeHTML(h)}</th>`).join("");
  const bodyRows = data
    .map(
      (row) =>
        `<tr>${headers.map((h) => `<td>${escapeHTML(String(row[h] || ""))}</td>`).join("")}</tr>`
    )
    .join("");

  return `
    <table>
      <thead>
        <tr>${headerRow}</tr>
      </thead>
      <tbody>
        ${bodyRows}
      </tbody>
    </table>
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHTML(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Generate PDF from HTML (placeholder - requires external service)
 * Options:
 * 1. Use Puppeteer (requires headless browser)
 * 2. Use html2pdf library
 * 3. Use external API like html2pdf.com
 */
export async function generatePDFFromHTML(
  html: string,
  filename: string
): Promise<Buffer> {
  // TODO: Implement PDF generation
  // For now, return a placeholder
  console.log(`[PDF Export] Would generate PDF: ${filename}`);
  return Buffer.from("PDF generation not yet implemented");
}

/**
 * Export report as PDF
 */
export async function exportReportAsPDF(
  organizationId: number,
  reportId: string,
  organizationName?: string
): Promise<{ html: string; filename: string }> {
  try {
    const html = await generateReportHTML(organizationId, reportId, organizationName);
    const filename = `report_${reportId}_${new Date().toISOString().split("T")[0]}.pdf`;

    return { html, filename };
  } catch (error) {
    console.error("Error exporting report as PDF:", error);
    throw error;
  }
}
